#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <user> <password>"
  exit 1
fi

user="$1"
password="$2"

response=$(curl -X -s -S \
POST -H "Content-Type: application/x-www-form-urlencoded" \
-d "username=$user&password=$password" \
http://localhost:8080/login)

echo "$response"
