#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 <token> <user_id> <url>"
  exit 1
fi

token="$1"
user_id="$2"
url="$3"

response=$(curl -X POST -s -S -H "Content-Type: application/json" \
  --cookie "jort_url_token=$token" \
  --cookie "jort_user_id=$user_id" \
  --data "{\"url\": \"$url\"}" \
  http://localhost:8080/url)

echo "$response"
